.\"                                      Hey, EMACS: -*- nroff -*-
.TH XPAD 1 "September 20, 2008"
.SH NAME
xpad \- A sticky notes application for GTK+ 2.0
.PP
.SH SYNOPSIS
.B xpad
.RI [OPTIONS]
.PP
.SH DESCRIPTION
A sticky notes application for GTK+ 2.0.
.PP
.SH OPTIONS
.TP
.B \-v, \-\-version
Display version information.
.TP
.B \-?, \-\-help
Display usage information.
.TP
.B \-h, \-\-hide
Hides existing pads on startup.  All pads will be hidden, so unless the tray icon is present or you also specify \-\-new, xpad will exit immediately.
.TP
.B \-s, \-\-show
Shows existing pads on startup.
.TP
.B \-t, \-\-toggle
Toggle between showing and hiding each of the existing pads on startup.
.TP
.B \-n, \-\-new
Open a new pad.
.TP
.B \-N, \-\-no-new
Prevents xpad from making a new pad on startup.  A new pad would be created if xpad is already running and is run again or if there are no old pads to load.
.TP
.B \-f, \-\-new-from-file=FILE
Create a new pad with the contents of a file
.TP
.B \-q, \-\-quit
Closes all open pads and terminates the xpad processes.
.PP
.SH AUTHOR
Written by Michael Terry <mike@mterry.name>.
